### ISSUE TITLE
Add GitHub Actions Workflow

### ISSUE THREAD

**Issue by josdem** [josdem/jmetadata#30]
As **a user**, I want to create a [Github actions workflow](https://docs.github.com/en/actions/writing-workflows/quickstart) **so that** I can run tests cases

**Acceptance Criteria**
- I can run tests in every PR
- I can run test in every merge to main branch
- I can see a GitHub actions workflow

**Example**
https://github.com/josdem/vetlog-spring-boot/blob/main/.github/workflows/main.yml

**Comment by Lemeri123** [comment]
@josdem assign this to me

**Comment by josdem** [comment]
> @josdem assign this to me

Hi @Lemeri123  absolutely, your collaboration is appreciated!

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/jmetadata/pull/38
