### ISSUE TITLE
Read LastFM key and secret from system environment

### ISSUE THREAD

**Issue by josdem** [josdem/jmetadata#34]
As **user**, I want to read [LastFM](https://www.last.fm/api/authentication) key and secret from local system environment **so that** I can improve security in the application

**Acceptance Criteria**
- I can export key to system environment like: `export KEY=myLastFMkey`
- I can export secret to system environment like: `export SECRET=myLastFMsecret`
- I avoid reading key and secret from this [class](https://github.com/josdem/jmetadata/blob/main/src/main/java/org/jas/Auth.java)
- All tests are passing

**Comment by Lemeri123** [comment]
hello @josdem am requesting for the LASTFM_KEY and LASTFM_SECRET APIs

**Comment by josdem** [comment]
> hello @josdem am requesting for the LASTFM_KEY and LASTFM_SECRET APIs

Hi @Lemeri123  the goal from this task is to read lastFM key and secret from [GitHub Actions secrets](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions) in order to do that we should be able to export them in system properties in both Linux and Windows platforms. With that said, if you want to take this task assume the KEY and SECRET are the following:

```bash
LASTFM_KEY=key
LASTFM_SECRET=secret
````

Then I will replace those values for the real ones.
Let me know if any questions.

**Comment by Lemeri123** [comment]
Ohhh okay then thats great because I just wanted them inorder to add them to my environmental variables for testing before I push the code

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/jmetadata/pull/45
